name: Save JSON file

on:
  workflow_dispatch:   # manual trigger

jobs:
  commit-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push JSON file
        run: |
          git add path/to/responses.json
          git commit -m "Update responses.json from action" || echo "No changes to commit"
          git push
